// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aerospike/backup-go/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mock := &MockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

type MockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessor) EXPECT() *MockProcessor_Expecter {
	return &MockProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type MockProcessor
func (_mock *MockProcessor) Process(token *models.Token) (*models.Token, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *models.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Token) (*models.Token, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Token) *models.Token); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Token) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - token *models.Token
func (_e *MockProcessor_Expecter) Process(token interface{}) *MockProcessor_Process_Call {
	return &MockProcessor_Process_Call{Call: _e.mock.On("Process", token)}
}

func (_c *MockProcessor_Process_Call) Run(run func(token *models.Token)) *MockProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Token
		if args[0] != nil {
			arg0 = args[0].(*models.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcessor_Process_Call) Return(token1 *models.Token, err error) *MockProcessor_Process_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *MockProcessor_Process_Call) RunAndReturn(run func(token *models.Token) (*models.Token, error)) *MockProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}
