// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aerospike/backup-go/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockWriter
func (_mock *MockWriter) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWriter_Expecter) Close() *MockWriter_Close_Call {
	return &MockWriter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWriter_Close_Call) Run(run func()) *MockWriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWriter_Close_Call) Return(err error) *MockWriter_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_Close_Call) RunAndReturn(run func() error) *MockWriter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockWriter
func (_mock *MockWriter) Write(token *models.Token) (int, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Token) (int, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Token) int); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Token) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - token *models.Token
func (_e *MockWriter_Expecter) Write(token interface{}) *MockWriter_Write_Call {
	return &MockWriter_Write_Call{Call: _e.mock.On("Write", token)}
}

func (_c *MockWriter_Write_Call) Run(run func(token *models.Token)) *MockWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Token
		if args[0] != nil {
			arg0 = args[0].(*models.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWriter_Write_Call) Return(n int, err error) *MockWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWriter_Write_Call) RunAndReturn(run func(token *models.Token) (int, error)) *MockWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
