// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataReader is an autogenerated mock type for the DataReader type
type DataReader struct {
	mock.Mock
}

type DataReader_Expecter struct {
	mock *mock.Mock
}

func (_m *DataReader) EXPECT() *DataReader_Expecter {
	return &DataReader_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields:
func (_m *DataReader) Cancel() {
	_m.Called()
}

// DataReader_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type DataReader_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
func (_e *DataReader_Expecter) Cancel() *DataReader_Cancel_Call {
	return &DataReader_Cancel_Call{Call: _e.mock.On("Cancel")}
}

func (_c *DataReader_Cancel_Call) Run(run func()) *DataReader_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DataReader_Cancel_Call) Return() *DataReader_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *DataReader_Cancel_Call) RunAndReturn(run func()) *DataReader_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields:
func (_m *DataReader) Read() (interface{}, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() (interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DataReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type DataReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *DataReader_Expecter) Read() *DataReader_Read_Call {
	return &DataReader_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *DataReader_Read_Call) Run(run func()) *DataReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DataReader_Read_Call) Return(_a0 interface{}, _a1 error) *DataReader_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DataReader_Read_Call) RunAndReturn(run func() (interface{}, error)) *DataReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewDataReader creates a new instance of DataReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataReader {
	mock := &DataReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
