// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Writer is an autogenerated mock type for the Writer type
type Writer[T interface{}] struct {
	mock.Mock
}

type Writer_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *Writer[T]) EXPECT() *Writer_Expecter[T] {
	return &Writer_Expecter[T]{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields:
func (_m *Writer[T]) Cancel() {
	_m.Called()
}

// Writer_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type Writer_Cancel_Call[T interface{}] struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
func (_e *Writer_Expecter[T]) Cancel() *Writer_Cancel_Call[T] {
	return &Writer_Cancel_Call[T]{Call: _e.mock.On("Cancel")}
}

func (_c *Writer_Cancel_Call[T]) Run(run func()) *Writer_Cancel_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Writer_Cancel_Call[T]) Return() *Writer_Cancel_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Cancel_Call[T]) RunAndReturn(run func()) *Writer_Cancel_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *Writer[T]) Write(_a0 T) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(T) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Writer_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type Writer_Write_Call[T interface{}] struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 T
func (_e *Writer_Expecter[T]) Write(_a0 interface{}) *Writer_Write_Call[T] {
	return &Writer_Write_Call[T]{Call: _e.mock.On("Write", _a0)}
}

func (_c *Writer_Write_Call[T]) Run(run func(_a0 T)) *Writer_Write_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *Writer_Write_Call[T]) Return(_a0 error) *Writer_Write_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Write_Call[T]) RunAndReturn(run func(T) error) *Writer_Write_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewWriter creates a new instance of Writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriter[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *Writer[T] {
	mock := &Writer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
