linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - unused
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc # pre-allocate slices with define size if the slice size is known in advance
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - lll
    - wsl # While space linter

run:
  issues-exit-code: 1

# Test exclusion examples
issues:
  exclude-rules:
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at' # Allow idiomatic shadowing of err and ctx
      linters: 
      - govet
    - text: 'exported: type name will be used as backup.(BackupStats|BackupHandler|BackupConfig) by other packages, and that stutters' # Allow stuttering for backup types
      linters: 
      - revive
    - path: '(.+)test\.go'
      linters:
      - govet # Test code field alignment for sake of space is not a concern
      - dupl
      - goconst # Many test cases are small and have repeated strings that don't need to be constants
      - wsl # Test code should be allowed to cuddle if statements, generated tests do this
    - path: '(.+)test\.go'
      text: importShadow