version: "2"
run:
  issues-exit-code: 1

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - modernize
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - sloglint
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wsl_v5
  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 21
    gosec:
      excludes:
        - G115
    govet:
      enable:
        - shadow
    nolintlint:
      require-explanation: true
      require-specific: true
    sloglint:
      attr-only: true
      key-naming-case: camel
      forbidden-keys:
        - err # let's only use slog.Any("error", err)
    usetesting:
      context-background: true
      context-todo: true
      os-temp-dir: true
      os-setenv: true
    wsl_v5:
      disable:
        - assign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - revive
        text: 'exported: type name will be used as backup.(BackupStats|BackupHandler|BackupConfig|BackupToDirectoryConfig|BackupToDirectoryStats|BackupToDirectoryHandler) by other packages, and that stutters'
      - linters:
          - revive
        path: ^io/storage/common/
      - linters:
          - dupl
          - goconst
          - govet
          - lll
          - wsl_v5
          - prealloc
        path: (.+)test\.go
      - path: (.+)test\.go
        text: importShadow
      - path: (.+)test\.go
        text: 'G404: Use of weak random number generator'
    paths:
      - main
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - main
      - third_party$
      - builtin$
      - examples$
