all: true
filename: "{{.InterfaceName}}_mock.go"
structname: "Mock{{.InterfaceName}}"
formatter: goimports
template: testify
packages:
  github.com/aerospike/backup-go:
    config:
      dir: mocks
      exclude-subpkg-regex:
        - ClientOpt
      pkgname: mocks
  github.com/aerospike/backup-go/pkg/asinfo:
    config:
      dir: ./pkg/asinfo/mocks
      pkgname: mocks
  github.com/aerospike/backup-go/io/aerospike:
    config:
      dir: ./io/aerospike/mocks
      pkgname: mocks
  github.com/aerospike/backup-go/io/aerospike/xdr:
    config:
      dir: ./io/aerospike/xdr/mocks
      pkgname: mocks
  github.com/aerospike/backup-go/io/encoding/asb:
    config:
      dir: ./io/encoding/asb/mocks
      pkgname: mocks
  github.com/aerospike/backup-go/io/storage/internal:
    config:
      dir: ./io/storage/internal/mocks
      pkgname: mocks
  github.com/aerospike/backup-go/io/storage/options:
    config:
      exclude-subpkg-regex:
        - Opt
      dir: ./io/storage/options/mocks
      pkgname: mocks
  github.com/aerospike/backup-go/pipe:
    config:
      dir: ./pipe/mocks
      pkgname: mocks
  github.com/aerospike/backup-go/pkg/secret-agent/connection:
    config:
      dir: ./pkg/secret-agent/connection/mocks
      pkgname: mocks
  github.com/aerospike/backup-go/io/storage/aws/s3:
    config:
      dir: ./io/storage/aws/s3/mocks
      pkgname: mocks
