// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteBlob provides a mock function for the type MockClient
func (_mock *MockClient) DeleteBlob(ctx context.Context, containerName string, blobName string, o *azblob.DeleteBlobOptions) (azblob.DeleteBlobResponse, error) {
	ret := _mock.Called(ctx, containerName, blobName, o)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 azblob.DeleteBlobResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *azblob.DeleteBlobOptions) (azblob.DeleteBlobResponse, error)); ok {
		return returnFunc(ctx, containerName, blobName, o)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *azblob.DeleteBlobOptions) azblob.DeleteBlobResponse); ok {
		r0 = returnFunc(ctx, containerName, blobName, o)
	} else {
		r0 = ret.Get(0).(azblob.DeleteBlobResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *azblob.DeleteBlobOptions) error); ok {
		r1 = returnFunc(ctx, containerName, blobName, o)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type MockClient_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - ctx
//   - containerName
//   - blobName
//   - o
func (_e *MockClient_Expecter) DeleteBlob(ctx interface{}, containerName interface{}, blobName interface{}, o interface{}) *MockClient_DeleteBlob_Call {
	return &MockClient_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", ctx, containerName, blobName, o)}
}

func (_c *MockClient_DeleteBlob_Call) Run(run func(ctx context.Context, containerName string, blobName string, o *azblob.DeleteBlobOptions)) *MockClient_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*azblob.DeleteBlobOptions))
	})
	return _c
}

func (_c *MockClient_DeleteBlob_Call) Return(v azblob.DeleteBlobResponse, err error) *MockClient_DeleteBlob_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_DeleteBlob_Call) RunAndReturn(run func(ctx context.Context, containerName string, blobName string, o *azblob.DeleteBlobOptions) (azblob.DeleteBlobResponse, error)) *MockClient_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadStream provides a mock function for the type MockClient
func (_mock *MockClient) DownloadStream(ctx context.Context, containerName string, blobName string, o *azblob.DownloadStreamOptions) (azblob.DownloadStreamResponse, error) {
	ret := _mock.Called(ctx, containerName, blobName, o)

	if len(ret) == 0 {
		panic("no return value specified for DownloadStream")
	}

	var r0 azblob.DownloadStreamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *azblob.DownloadStreamOptions) (azblob.DownloadStreamResponse, error)); ok {
		return returnFunc(ctx, containerName, blobName, o)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *azblob.DownloadStreamOptions) azblob.DownloadStreamResponse); ok {
		r0 = returnFunc(ctx, containerName, blobName, o)
	} else {
		r0 = ret.Get(0).(azblob.DownloadStreamResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *azblob.DownloadStreamOptions) error); ok {
		r1 = returnFunc(ctx, containerName, blobName, o)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_DownloadStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadStream'
type MockClient_DownloadStream_Call struct {
	*mock.Call
}

// DownloadStream is a helper method to define mock.On call
//   - ctx
//   - containerName
//   - blobName
//   - o
func (_e *MockClient_Expecter) DownloadStream(ctx interface{}, containerName interface{}, blobName interface{}, o interface{}) *MockClient_DownloadStream_Call {
	return &MockClient_DownloadStream_Call{Call: _e.mock.On("DownloadStream", ctx, containerName, blobName, o)}
}

func (_c *MockClient_DownloadStream_Call) Run(run func(ctx context.Context, containerName string, blobName string, o *azblob.DownloadStreamOptions)) *MockClient_DownloadStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*azblob.DownloadStreamOptions))
	})
	return _c
}

func (_c *MockClient_DownloadStream_Call) Return(v azblob.DownloadStreamResponse, err error) *MockClient_DownloadStream_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_DownloadStream_Call) RunAndReturn(run func(ctx context.Context, containerName string, blobName string, o *azblob.DownloadStreamOptions) (azblob.DownloadStreamResponse, error)) *MockClient_DownloadStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewListBlobsFlatPager provides a mock function for the type MockClient
func (_mock *MockClient) NewListBlobsFlatPager(containerName string, o *azblob.ListBlobsFlatOptions) *runtime.Pager[azblob.ListBlobsFlatResponse] {
	ret := _mock.Called(containerName, o)

	if len(ret) == 0 {
		panic("no return value specified for NewListBlobsFlatPager")
	}

	var r0 *runtime.Pager[azblob.ListBlobsFlatResponse]
	if returnFunc, ok := ret.Get(0).(func(string, *azblob.ListBlobsFlatOptions) *runtime.Pager[azblob.ListBlobsFlatResponse]); ok {
		r0 = returnFunc(containerName, o)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.Pager[azblob.ListBlobsFlatResponse])
		}
	}
	return r0
}

// MockClient_NewListBlobsFlatPager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewListBlobsFlatPager'
type MockClient_NewListBlobsFlatPager_Call struct {
	*mock.Call
}

// NewListBlobsFlatPager is a helper method to define mock.On call
//   - containerName
//   - o
func (_e *MockClient_Expecter) NewListBlobsFlatPager(containerName interface{}, o interface{}) *MockClient_NewListBlobsFlatPager_Call {
	return &MockClient_NewListBlobsFlatPager_Call{Call: _e.mock.On("NewListBlobsFlatPager", containerName, o)}
}

func (_c *MockClient_NewListBlobsFlatPager_Call) Run(run func(containerName string, o *azblob.ListBlobsFlatOptions)) *MockClient_NewListBlobsFlatPager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*azblob.ListBlobsFlatOptions))
	})
	return _c
}

func (_c *MockClient_NewListBlobsFlatPager_Call) Return(pager *runtime.Pager[azblob.ListBlobsFlatResponse]) *MockClient_NewListBlobsFlatPager_Call {
	_c.Call.Return(pager)
	return _c
}

func (_c *MockClient_NewListBlobsFlatPager_Call) RunAndReturn(run func(containerName string, o *azblob.ListBlobsFlatOptions) *runtime.Pager[azblob.ListBlobsFlatResponse]) *MockClient_NewListBlobsFlatPager_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceClient provides a mock function for the type MockClient
func (_mock *MockClient) ServiceClient() *service.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceClient")
	}

	var r0 *service.Client
	if returnFunc, ok := ret.Get(0).(func() *service.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Client)
		}
	}
	return r0
}

// MockClient_ServiceClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceClient'
type MockClient_ServiceClient_Call struct {
	*mock.Call
}

// ServiceClient is a helper method to define mock.On call
func (_e *MockClient_Expecter) ServiceClient() *MockClient_ServiceClient_Call {
	return &MockClient_ServiceClient_Call{Call: _e.mock.On("ServiceClient")}
}

func (_c *MockClient_ServiceClient_Call) Run(run func()) *MockClient_ServiceClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ServiceClient_Call) Return(client *service.Client) *MockClient_ServiceClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockClient_ServiceClient_Call) RunAndReturn(run func() *service.Client) *MockClient_ServiceClient_Call {
	_c.Call.Return(run)
	return _c
}
