// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewMocks3Client creates a new instance of Mocks3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocks3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocks3Client {
	mock := &Mocks3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mocks3Client is an autogenerated mock type for the s3Client type
type Mocks3Client struct {
	mock.Mock
}

type Mocks3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Mocks3Client) EXPECT() *Mocks3Client_Expecter {
	return &Mocks3Client_Expecter{mock: &_m.Mock}
}

// AbortMultipartUpload provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) AbortMultipartUpload(ctx context.Context, params *s3.AbortMultipartUploadInput, optFns ...func(*s3.Options)) (*s3.AbortMultipartUploadOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AbortMultipartUpload")
	}

	var r0 *s3.AbortMultipartUploadOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.AbortMultipartUploadInput, ...func(*s3.Options)) (*s3.AbortMultipartUploadOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.AbortMultipartUploadInput, ...func(*s3.Options)) *s3.AbortMultipartUploadOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.AbortMultipartUploadOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.AbortMultipartUploadInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_AbortMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortMultipartUpload'
type Mocks3Client_AbortMultipartUpload_Call struct {
	*mock.Call
}

// AbortMultipartUpload is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) AbortMultipartUpload(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_AbortMultipartUpload_Call {
	return &Mocks3Client_AbortMultipartUpload_Call{Call: _e.mock.On("AbortMultipartUpload",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_AbortMultipartUpload_Call) Run(run func(ctx context.Context, params *s3.AbortMultipartUploadInput, optFns ...func(*s3.Options))) *Mocks3Client_AbortMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.AbortMultipartUploadInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_AbortMultipartUpload_Call) Return(abortMultipartUploadOutput *s3.AbortMultipartUploadOutput, err error) *Mocks3Client_AbortMultipartUpload_Call {
	_c.Call.Return(abortMultipartUploadOutput, err)
	return _c
}

func (_c *Mocks3Client_AbortMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, params *s3.AbortMultipartUploadInput, optFns ...func(*s3.Options)) (*s3.AbortMultipartUploadOutput, error)) *Mocks3Client_AbortMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteMultipartUpload provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) CompleteMultipartUpload(ctx context.Context, params *s3.CompleteMultipartUploadInput, optFns ...func(*s3.Options)) (*s3.CompleteMultipartUploadOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CompleteMultipartUpload")
	}

	var r0 *s3.CompleteMultipartUploadOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CompleteMultipartUploadInput, ...func(*s3.Options)) (*s3.CompleteMultipartUploadOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CompleteMultipartUploadInput, ...func(*s3.Options)) *s3.CompleteMultipartUploadOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.CompleteMultipartUploadOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.CompleteMultipartUploadInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_CompleteMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteMultipartUpload'
type Mocks3Client_CompleteMultipartUpload_Call struct {
	*mock.Call
}

// CompleteMultipartUpload is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) CompleteMultipartUpload(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_CompleteMultipartUpload_Call {
	return &Mocks3Client_CompleteMultipartUpload_Call{Call: _e.mock.On("CompleteMultipartUpload",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_CompleteMultipartUpload_Call) Run(run func(ctx context.Context, params *s3.CompleteMultipartUploadInput, optFns ...func(*s3.Options))) *Mocks3Client_CompleteMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.CompleteMultipartUploadInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_CompleteMultipartUpload_Call) Return(completeMultipartUploadOutput *s3.CompleteMultipartUploadOutput, err error) *Mocks3Client_CompleteMultipartUpload_Call {
	_c.Call.Return(completeMultipartUploadOutput, err)
	return _c
}

func (_c *Mocks3Client_CompleteMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, params *s3.CompleteMultipartUploadInput, optFns ...func(*s3.Options)) (*s3.CompleteMultipartUploadOutput, error)) *Mocks3Client_CompleteMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMultipartUpload provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) CreateMultipartUpload(ctx context.Context, params *s3.CreateMultipartUploadInput, optFns ...func(*s3.Options)) (*s3.CreateMultipartUploadOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateMultipartUpload")
	}

	var r0 *s3.CreateMultipartUploadOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CreateMultipartUploadInput, ...func(*s3.Options)) (*s3.CreateMultipartUploadOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CreateMultipartUploadInput, ...func(*s3.Options)) *s3.CreateMultipartUploadOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.CreateMultipartUploadOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.CreateMultipartUploadInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_CreateMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMultipartUpload'
type Mocks3Client_CreateMultipartUpload_Call struct {
	*mock.Call
}

// CreateMultipartUpload is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) CreateMultipartUpload(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_CreateMultipartUpload_Call {
	return &Mocks3Client_CreateMultipartUpload_Call{Call: _e.mock.On("CreateMultipartUpload",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_CreateMultipartUpload_Call) Run(run func(ctx context.Context, params *s3.CreateMultipartUploadInput, optFns ...func(*s3.Options))) *Mocks3Client_CreateMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.CreateMultipartUploadInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_CreateMultipartUpload_Call) Return(createMultipartUploadOutput *s3.CreateMultipartUploadOutput, err error) *Mocks3Client_CreateMultipartUpload_Call {
	_c.Call.Return(createMultipartUploadOutput, err)
	return _c
}

func (_c *Mocks3Client_CreateMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, params *s3.CreateMultipartUploadInput, optFns ...func(*s3.Options)) (*s3.CreateMultipartUploadOutput, error)) *Mocks3Client_CreateMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) DeleteObject(ctx context.Context, params *s3.DeleteObjectInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 *s3.DeleteObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) *s3.DeleteObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.DeleteObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type Mocks3Client_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) DeleteObject(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_DeleteObject_Call {
	return &Mocks3Client_DeleteObject_Call{Call: _e.mock.On("DeleteObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_DeleteObject_Call) Run(run func(ctx context.Context, params *s3.DeleteObjectInput, optFns ...func(*s3.Options))) *Mocks3Client_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.DeleteObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_DeleteObject_Call) Return(deleteObjectOutput *s3.DeleteObjectOutput, err error) *Mocks3Client_DeleteObject_Call {
	_c.Call.Return(deleteObjectOutput, err)
	return _c
}

func (_c *Mocks3Client_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.DeleteObjectInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)) *Mocks3Client_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *s3.GetObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) *s3.GetObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type Mocks3Client_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) GetObject(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_GetObject_Call {
	return &Mocks3Client_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_GetObject_Call) Run(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options))) *Mocks3Client_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.GetObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_GetObject_Call) Return(getObjectOutput *s3.GetObjectOutput, err error) *Mocks3Client_GetObject_Call {
	_c.Call.Return(getObjectOutput, err)
	return _c
}

func (_c *Mocks3Client_GetObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error)) *Mocks3Client_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// HeadBucket provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) HeadBucket(ctx context.Context, params *s3.HeadBucketInput, optFns ...func(*s3.Options)) (*s3.HeadBucketOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HeadBucket")
	}

	var r0 *s3.HeadBucketOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) (*s3.HeadBucketOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) *s3.HeadBucketOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.HeadBucketOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_HeadBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadBucket'
type Mocks3Client_HeadBucket_Call struct {
	*mock.Call
}

// HeadBucket is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) HeadBucket(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_HeadBucket_Call {
	return &Mocks3Client_HeadBucket_Call{Call: _e.mock.On("HeadBucket",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_HeadBucket_Call) Run(run func(ctx context.Context, params *s3.HeadBucketInput, optFns ...func(*s3.Options))) *Mocks3Client_HeadBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.HeadBucketInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_HeadBucket_Call) Return(headBucketOutput *s3.HeadBucketOutput, err error) *Mocks3Client_HeadBucket_Call {
	_c.Call.Return(headBucketOutput, err)
	return _c
}

func (_c *Mocks3Client_HeadBucket_Call) RunAndReturn(run func(ctx context.Context, params *s3.HeadBucketInput, optFns ...func(*s3.Options)) (*s3.HeadBucketOutput, error)) *Mocks3Client_HeadBucket_Call {
	_c.Call.Return(run)
	return _c
}

// HeadObject provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) HeadObject(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HeadObject")
	}

	var r0 *s3.HeadObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) (*s3.HeadObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) *s3.HeadObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.HeadObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_HeadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadObject'
type Mocks3Client_HeadObject_Call struct {
	*mock.Call
}

// HeadObject is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) HeadObject(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_HeadObject_Call {
	return &Mocks3Client_HeadObject_Call{Call: _e.mock.On("HeadObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_HeadObject_Call) Run(run func(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options))) *Mocks3Client_HeadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.HeadObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_HeadObject_Call) Return(headObjectOutput *s3.HeadObjectOutput, err error) *Mocks3Client_HeadObject_Call {
	_c.Call.Return(headObjectOutput, err)
	return _c
}

func (_c *Mocks3Client_HeadObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.HeadObjectInput, optFns ...func(*s3.Options)) (*s3.HeadObjectOutput, error)) *Mocks3Client_HeadObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjectsV2 provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) ListObjectsV2(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListObjectsV2")
	}

	var r0 *s3.ListObjectsV2Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) *s3.ListObjectsV2Output); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.ListObjectsV2Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_ListObjectsV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjectsV2'
type Mocks3Client_ListObjectsV2_Call struct {
	*mock.Call
}

// ListObjectsV2 is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) ListObjectsV2(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_ListObjectsV2_Call {
	return &Mocks3Client_ListObjectsV2_Call{Call: _e.mock.On("ListObjectsV2",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_ListObjectsV2_Call) Run(run func(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options))) *Mocks3Client_ListObjectsV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.ListObjectsV2Input), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_ListObjectsV2_Call) Return(listObjectsV2Output *s3.ListObjectsV2Output, err error) *Mocks3Client_ListObjectsV2_Call {
	_c.Call.Return(listObjectsV2Output, err)
	return _c
}

func (_c *Mocks3Client_ListObjectsV2_Call) RunAndReturn(run func(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)) *Mocks3Client_ListObjectsV2_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreObject provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) RestoreObject(ctx context.Context, params *s3.RestoreObjectInput, optFns ...func(*s3.Options)) (*s3.RestoreObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RestoreObject")
	}

	var r0 *s3.RestoreObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.RestoreObjectInput, ...func(*s3.Options)) (*s3.RestoreObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.RestoreObjectInput, ...func(*s3.Options)) *s3.RestoreObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.RestoreObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.RestoreObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_RestoreObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreObject'
type Mocks3Client_RestoreObject_Call struct {
	*mock.Call
}

// RestoreObject is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) RestoreObject(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_RestoreObject_Call {
	return &Mocks3Client_RestoreObject_Call{Call: _e.mock.On("RestoreObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_RestoreObject_Call) Run(run func(ctx context.Context, params *s3.RestoreObjectInput, optFns ...func(*s3.Options))) *Mocks3Client_RestoreObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.RestoreObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_RestoreObject_Call) Return(restoreObjectOutput *s3.RestoreObjectOutput, err error) *Mocks3Client_RestoreObject_Call {
	_c.Call.Return(restoreObjectOutput, err)
	return _c
}

func (_c *Mocks3Client_RestoreObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.RestoreObjectInput, optFns ...func(*s3.Options)) (*s3.RestoreObjectOutput, error)) *Mocks3Client_RestoreObject_Call {
	_c.Call.Return(run)
	return _c
}

// UploadPart provides a mock function for the type Mocks3Client
func (_mock *Mocks3Client) UploadPart(ctx context.Context, params *s3.UploadPartInput, optFns ...func(*s3.Options)) (*s3.UploadPartOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UploadPart")
	}

	var r0 *s3.UploadPartOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.UploadPartInput, ...func(*s3.Options)) (*s3.UploadPartOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.UploadPartInput, ...func(*s3.Options)) *s3.UploadPartOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.UploadPartOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.UploadPartInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mocks3Client_UploadPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadPart'
type Mocks3Client_UploadPart_Call struct {
	*mock.Call
}

// UploadPart is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *Mocks3Client_Expecter) UploadPart(ctx interface{}, params interface{}, optFns ...interface{}) *Mocks3Client_UploadPart_Call {
	return &Mocks3Client_UploadPart_Call{Call: _e.mock.On("UploadPart",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *Mocks3Client_UploadPart_Call) Run(run func(ctx context.Context, params *s3.UploadPartInput, optFns ...func(*s3.Options))) *Mocks3Client_UploadPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.UploadPartInput), variadicArgs...)
	})
	return _c
}

func (_c *Mocks3Client_UploadPart_Call) Return(uploadPartOutput *s3.UploadPartOutput, err error) *Mocks3Client_UploadPart_Call {
	_c.Call.Return(uploadPartOutput, err)
	return _c
}

func (_c *Mocks3Client_UploadPart_Call) RunAndReturn(run func(ctx context.Context, params *s3.UploadPartInput, optFns ...func(*s3.Options)) (*s3.UploadPartOutput, error)) *Mocks3Client_UploadPart_Call {
	_c.Call.Return(run)
	return _c
}
