// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockDataProcessor is an autogenerated mock type for the DataProcessor type
type MockDataProcessor[T interface{}] struct {
	mock.Mock
}

type MockDataProcessor_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockDataProcessor[T]) EXPECT() *MockDataProcessor_Expecter[T] {
	return &MockDataProcessor_Expecter[T]{mock: &_m.Mock}
}

// Process provides a mock function with given fields: _a0
func (_m *MockDataProcessor[T]) Process(_a0 T) (T, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(T) (T, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(T) T); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(T)
	}

	if rf, ok := ret.Get(1).(func(T) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockDataProcessor_Process_Call[T interface{}] struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - _a0 T
func (_e *MockDataProcessor_Expecter[T]) Process(_a0 interface{}) *MockDataProcessor_Process_Call[T] {
	return &MockDataProcessor_Process_Call[T]{Call: _e.mock.On("Process", _a0)}
}

func (_c *MockDataProcessor_Process_Call[T]) Run(run func(_a0 T)) *MockDataProcessor_Process_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *MockDataProcessor_Process_Call[T]) Return(_a0 T, _a1 error) *MockDataProcessor_Process_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataProcessor_Process_Call[T]) RunAndReturn(run func(T) (T, error)) *MockDataProcessor_Process_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockDataProcessor creates a new instance of MockDataProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataProcessor[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataProcessor[T] {
	mock := &MockDataProcessor[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
