// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aerospike/aerospike-tools-backup-lib/models"
	mock "github.com/stretchr/testify/mock"
)

// ASBEncoder is an autogenerated mock type for the ASBEncoder type
type ASBEncoder struct {
	mock.Mock
}

type ASBEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *ASBEncoder) EXPECT() *ASBEncoder_Expecter {
	return &ASBEncoder_Expecter{mock: &_m.Mock}
}

// EncodeToken provides a mock function with given fields: _a0
func (_m *ASBEncoder) EncodeToken(_a0 *models.Token) ([]byte, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for EncodeToken")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Token) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*models.Token) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Token) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ASBEncoder_EncodeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeToken'
type ASBEncoder_EncodeToken_Call struct {
	*mock.Call
}

// EncodeToken is a helper method to define mock.On call
//   - _a0 *models.Token
func (_e *ASBEncoder_Expecter) EncodeToken(_a0 interface{}) *ASBEncoder_EncodeToken_Call {
	return &ASBEncoder_EncodeToken_Call{Call: _e.mock.On("EncodeToken", _a0)}
}

func (_c *ASBEncoder_EncodeToken_Call) Run(run func(_a0 *models.Token)) *ASBEncoder_EncodeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Token))
	})
	return _c
}

func (_c *ASBEncoder_EncodeToken_Call) Return(_a0 []byte, _a1 error) *ASBEncoder_EncodeToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ASBEncoder_EncodeToken_Call) RunAndReturn(run func(*models.Token) ([]byte, error)) *ASBEncoder_EncodeToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirstMetaText provides a mock function with given fields:
func (_m *ASBEncoder) GetFirstMetaText() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFirstMetaText")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// ASBEncoder_GetFirstMetaText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstMetaText'
type ASBEncoder_GetFirstMetaText_Call struct {
	*mock.Call
}

// GetFirstMetaText is a helper method to define mock.On call
func (_e *ASBEncoder_Expecter) GetFirstMetaText() *ASBEncoder_GetFirstMetaText_Call {
	return &ASBEncoder_GetFirstMetaText_Call{Call: _e.mock.On("GetFirstMetaText")}
}

func (_c *ASBEncoder_GetFirstMetaText_Call) Run(run func()) *ASBEncoder_GetFirstMetaText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ASBEncoder_GetFirstMetaText_Call) Return(_a0 []byte) *ASBEncoder_GetFirstMetaText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ASBEncoder_GetFirstMetaText_Call) RunAndReturn(run func() []byte) *ASBEncoder_GetFirstMetaText_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespaceMetaText provides a mock function with given fields: namespace
func (_m *ASBEncoder) GetNamespaceMetaText(namespace string) []byte {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceMetaText")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// ASBEncoder_GetNamespaceMetaText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespaceMetaText'
type ASBEncoder_GetNamespaceMetaText_Call struct {
	*mock.Call
}

// GetNamespaceMetaText is a helper method to define mock.On call
//   - namespace string
func (_e *ASBEncoder_Expecter) GetNamespaceMetaText(namespace interface{}) *ASBEncoder_GetNamespaceMetaText_Call {
	return &ASBEncoder_GetNamespaceMetaText_Call{Call: _e.mock.On("GetNamespaceMetaText", namespace)}
}

func (_c *ASBEncoder_GetNamespaceMetaText_Call) Run(run func(namespace string)) *ASBEncoder_GetNamespaceMetaText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ASBEncoder_GetNamespaceMetaText_Call) Return(_a0 []byte) *ASBEncoder_GetNamespaceMetaText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ASBEncoder_GetNamespaceMetaText_Call) RunAndReturn(run func(string) []byte) *ASBEncoder_GetNamespaceMetaText_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersionText provides a mock function with given fields:
func (_m *ASBEncoder) GetVersionText() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersionText")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// ASBEncoder_GetVersionText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionText'
type ASBEncoder_GetVersionText_Call struct {
	*mock.Call
}

// GetVersionText is a helper method to define mock.On call
func (_e *ASBEncoder_Expecter) GetVersionText() *ASBEncoder_GetVersionText_Call {
	return &ASBEncoder_GetVersionText_Call{Call: _e.mock.On("GetVersionText")}
}

func (_c *ASBEncoder_GetVersionText_Call) Run(run func()) *ASBEncoder_GetVersionText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ASBEncoder_GetVersionText_Call) Return(_a0 []byte) *ASBEncoder_GetVersionText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ASBEncoder_GetVersionText_Call) RunAndReturn(run func() []byte) *ASBEncoder_GetVersionText_Call {
	_c.Call.Return(run)
	return _c
}

// NewASBEncoder creates a new instance of ASBEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewASBEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ASBEncoder {
	mock := &ASBEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
