// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aerospike/backup-go/pkg/asinfo/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackupInfo creates a new instance of MockBackupInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackupInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackupInfo {
	mock := &MockBackupInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackupInfo is an autogenerated mock type for the BackupInfo type
type MockBackupInfo struct {
	mock.Mock
}

type MockBackupInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackupInfo) EXPECT() *MockBackupInfo_Expecter {
	return &MockBackupInfo_Expecter{mock: &_m.Mock}
}

// GetBackupStatus provides a mock function for the type MockBackupInfo
func (_mock *MockBackupInfo) GetBackupStatus(ctx context.Context) (float64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupStatus")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (float64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupInfo_GetBackupStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackupStatus'
type MockBackupInfo_GetBackupStatus_Call struct {
	*mock.Call
}

// GetBackupStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackupInfo_Expecter) GetBackupStatus(ctx interface{}) *MockBackupInfo_GetBackupStatus_Call {
	return &MockBackupInfo_GetBackupStatus_Call{Call: _e.mock.On("GetBackupStatus", ctx)}
}

func (_c *MockBackupInfo_GetBackupStatus_Call) Run(run func(ctx context.Context)) *MockBackupInfo_GetBackupStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackupInfo_GetBackupStatus_Call) Return(f float64, err error) *MockBackupInfo_GetBackupStatus_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockBackupInfo_GetBackupStatus_Call) RunAndReturn(run func(ctx context.Context) (float64, error)) *MockBackupInfo_GetBackupStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetRestoreStatus provides a mock function for the type MockBackupInfo
func (_mock *MockBackupInfo) GetRestoreStatus(ctx context.Context, namespace string) (string, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetRestoreStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupInfo_GetRestoreStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRestoreStatus'
type MockBackupInfo_GetRestoreStatus_Call struct {
	*mock.Call
}

// GetRestoreStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockBackupInfo_Expecter) GetRestoreStatus(ctx interface{}, namespace interface{}) *MockBackupInfo_GetRestoreStatus_Call {
	return &MockBackupInfo_GetRestoreStatus_Call{Call: _e.mock.On("GetRestoreStatus", ctx, namespace)}
}

func (_c *MockBackupInfo_GetRestoreStatus_Call) Run(run func(ctx context.Context, namespace string)) *MockBackupInfo_GetRestoreStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupInfo_GetRestoreStatus_Call) Return(s string, err error) *MockBackupInfo_GetRestoreStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBackupInfo_GetRestoreStatus_Call) RunAndReturn(run func(ctx context.Context, namespace string) (string, error)) *MockBackupInfo_GetRestoreStatus_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareServerRestore provides a mock function for the type MockBackupInfo
func (_mock *MockBackupInfo) PrepareServerRestore(ctx context.Context, jobID string, namespace string) error {
	ret := _mock.Called(ctx, jobID, namespace)

	if len(ret) == 0 {
		panic("no return value specified for PrepareServerRestore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, jobID, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackupInfo_PrepareServerRestore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareServerRestore'
type MockBackupInfo_PrepareServerRestore_Call struct {
	*mock.Call
}

// PrepareServerRestore is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
//   - namespace string
func (_e *MockBackupInfo_Expecter) PrepareServerRestore(ctx interface{}, jobID interface{}, namespace interface{}) *MockBackupInfo_PrepareServerRestore_Call {
	return &MockBackupInfo_PrepareServerRestore_Call{Call: _e.mock.On("PrepareServerRestore", ctx, jobID, namespace)}
}

func (_c *MockBackupInfo_PrepareServerRestore_Call) Run(run func(ctx context.Context, jobID string, namespace string)) *MockBackupInfo_PrepareServerRestore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackupInfo_PrepareServerRestore_Call) Return(err error) *MockBackupInfo_PrepareServerRestore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackupInfo_PrepareServerRestore_Call) RunAndReturn(run func(ctx context.Context, jobID string, namespace string) error) *MockBackupInfo_PrepareServerRestore_Call {
	_c.Call.Return(run)
	return _c
}

// StartServerBackup provides a mock function for the type MockBackupInfo
func (_mock *MockBackupInfo) StartServerBackup(ctx context.Context, request *models.RequestBackup) (string, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for StartServerBackup")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RequestBackup) (string, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RequestBackup) string); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.RequestBackup) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupInfo_StartServerBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartServerBackup'
type MockBackupInfo_StartServerBackup_Call struct {
	*mock.Call
}

// StartServerBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - request *models.RequestBackup
func (_e *MockBackupInfo_Expecter) StartServerBackup(ctx interface{}, request interface{}) *MockBackupInfo_StartServerBackup_Call {
	return &MockBackupInfo_StartServerBackup_Call{Call: _e.mock.On("StartServerBackup", ctx, request)}
}

func (_c *MockBackupInfo_StartServerBackup_Call) Run(run func(ctx context.Context, request *models.RequestBackup)) *MockBackupInfo_StartServerBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.RequestBackup
		if args[1] != nil {
			arg1 = args[1].(*models.RequestBackup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupInfo_StartServerBackup_Call) Return(s string, err error) *MockBackupInfo_StartServerBackup_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBackupInfo_StartServerBackup_Call) RunAndReturn(run func(ctx context.Context, request *models.RequestBackup) (string, error)) *MockBackupInfo_StartServerBackup_Call {
	_c.Call.Return(run)
	return _c
}

// StartServerRestore provides a mock function for the type MockBackupInfo
func (_mock *MockBackupInfo) StartServerRestore(ctx context.Context, request *models.RequestRestore) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for StartServerRestore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RequestRestore) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackupInfo_StartServerRestore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartServerRestore'
type MockBackupInfo_StartServerRestore_Call struct {
	*mock.Call
}

// StartServerRestore is a helper method to define mock.On call
//   - ctx context.Context
//   - request *models.RequestRestore
func (_e *MockBackupInfo_Expecter) StartServerRestore(ctx interface{}, request interface{}) *MockBackupInfo_StartServerRestore_Call {
	return &MockBackupInfo_StartServerRestore_Call{Call: _e.mock.On("StartServerRestore", ctx, request)}
}

func (_c *MockBackupInfo_StartServerRestore_Call) Run(run func(ctx context.Context, request *models.RequestRestore)) *MockBackupInfo_StartServerRestore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.RequestRestore
		if args[1] != nil {
			arg1 = args[1].(*models.RequestRestore)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupInfo_StartServerRestore_Call) Return(err error) *MockBackupInfo_StartServerRestore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackupInfo_StartServerRestore_Call) RunAndReturn(run func(ctx context.Context, request *models.RequestRestore) error) *MockBackupInfo_StartServerRestore_Call {
	_c.Call.Return(run)
	return _c
}
