// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aerospike/backup-go/models"
	mock "github.com/stretchr/testify/mock"
)

// MockEncoder is an autogenerated mock type for the Encoder type
type MockEncoder struct {
	mock.Mock
}

type MockEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncoder) EXPECT() *MockEncoder_Expecter {
	return &MockEncoder_Expecter{mock: &_m.Mock}
}

// EncodeToken provides a mock function with given fields: _a0
func (_m *MockEncoder) EncodeToken(_a0 *models.Token) ([]byte, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for EncodeToken")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Token) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*models.Token) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Token) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEncoder_EncodeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeToken'
type MockEncoder_EncodeToken_Call struct {
	*mock.Call
}

// EncodeToken is a helper method to define mock.On call
//   - _a0 *models.Token
func (_e *MockEncoder_Expecter) EncodeToken(_a0 interface{}) *MockEncoder_EncodeToken_Call {
	return &MockEncoder_EncodeToken_Call{Call: _e.mock.On("EncodeToken", _a0)}
}

func (_c *MockEncoder_EncodeToken_Call) Run(run func(_a0 *models.Token)) *MockEncoder_EncodeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Token))
	})
	return _c
}

func (_c *MockEncoder_EncodeToken_Call) Return(_a0 []byte, _a1 error) *MockEncoder_EncodeToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEncoder_EncodeToken_Call) RunAndReturn(run func(*models.Token) ([]byte, error)) *MockEncoder_EncodeToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateFilename provides a mock function with given fields:
func (_m *MockEncoder) GenerateFilename() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateFilename")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEncoder_GenerateFilename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFilename'
type MockEncoder_GenerateFilename_Call struct {
	*mock.Call
}

// GenerateFilename is a helper method to define mock.On call
func (_e *MockEncoder_Expecter) GenerateFilename() *MockEncoder_GenerateFilename_Call {
	return &MockEncoder_GenerateFilename_Call{Call: _e.mock.On("GenerateFilename")}
}

func (_c *MockEncoder_GenerateFilename_Call) Run(run func()) *MockEncoder_GenerateFilename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEncoder_GenerateFilename_Call) Return(_a0 string) *MockEncoder_GenerateFilename_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEncoder_GenerateFilename_Call) RunAndReturn(run func() string) *MockEncoder_GenerateFilename_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeader provides a mock function with given fields:
func (_m *MockEncoder) GetHeader() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHeader")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MockEncoder_GetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeader'
type MockEncoder_GetHeader_Call struct {
	*mock.Call
}

// GetHeader is a helper method to define mock.On call
func (_e *MockEncoder_Expecter) GetHeader() *MockEncoder_GetHeader_Call {
	return &MockEncoder_GetHeader_Call{Call: _e.mock.On("GetHeader")}
}

func (_c *MockEncoder_GetHeader_Call) Run(run func()) *MockEncoder_GetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEncoder_GetHeader_Call) Return(_a0 []byte) *MockEncoder_GetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEncoder_GetHeader_Call) RunAndReturn(run func() []byte) *MockEncoder_GetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEncoder creates a new instance of MockEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncoder {
	mock := &MockEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
