// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockinfoGetter creates a new instance of MockinfoGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockinfoGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockinfoGetter {
	mock := &MockinfoGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockinfoGetter is an autogenerated mock type for the infoGetter type
type MockinfoGetter struct {
	mock.Mock
}

type MockinfoGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockinfoGetter) EXPECT() *MockinfoGetter_Expecter {
	return &MockinfoGetter_Expecter{mock: &_m.Mock}
}

// GetRackNodes provides a mock function for the type MockinfoGetter
func (_mock *MockinfoGetter) GetRackNodes(rackID int) ([]string, error) {
	ret := _mock.Called(rackID)

	if len(ret) == 0 {
		panic("no return value specified for GetRackNodes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]string, error)); ok {
		return returnFunc(rackID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []string); ok {
		r0 = returnFunc(rackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(rackID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockinfoGetter_GetRackNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRackNodes'
type MockinfoGetter_GetRackNodes_Call struct {
	*mock.Call
}

// GetRackNodes is a helper method to define mock.On call
//   - rackID
func (_e *MockinfoGetter_Expecter) GetRackNodes(rackID interface{}) *MockinfoGetter_GetRackNodes_Call {
	return &MockinfoGetter_GetRackNodes_Call{Call: _e.mock.On("GetRackNodes", rackID)}
}

func (_c *MockinfoGetter_GetRackNodes_Call) Run(run func(rackID int)) *MockinfoGetter_GetRackNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockinfoGetter_GetRackNodes_Call) Return(strings []string, err error) *MockinfoGetter_GetRackNodes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockinfoGetter_GetRackNodes_Call) RunAndReturn(run func(rackID int) ([]string, error)) *MockinfoGetter_GetRackNodes_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecordCount provides a mock function for the type MockinfoGetter
func (_mock *MockinfoGetter) GetRecordCount(namespace string, sets []string) (uint64, error) {
	ret := _mock.Called(namespace, sets)

	if len(ret) == 0 {
		panic("no return value specified for GetRecordCount")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) (uint64, error)); ok {
		return returnFunc(namespace, sets)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string) uint64); ok {
		r0 = returnFunc(namespace, sets)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = returnFunc(namespace, sets)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockinfoGetter_GetRecordCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecordCount'
type MockinfoGetter_GetRecordCount_Call struct {
	*mock.Call
}

// GetRecordCount is a helper method to define mock.On call
//   - namespace
//   - sets
func (_e *MockinfoGetter_Expecter) GetRecordCount(namespace interface{}, sets interface{}) *MockinfoGetter_GetRecordCount_Call {
	return &MockinfoGetter_GetRecordCount_Call{Call: _e.mock.On("GetRecordCount", namespace, sets)}
}

func (_c *MockinfoGetter_GetRecordCount_Call) Run(run func(namespace string, sets []string)) *MockinfoGetter_GetRecordCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockinfoGetter_GetRecordCount_Call) Return(v uint64, err error) *MockinfoGetter_GetRecordCount_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockinfoGetter_GetRecordCount_Call) RunAndReturn(run func(namespace string, sets []string) (uint64, error)) *MockinfoGetter_GetRecordCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type MockinfoGetter
func (_mock *MockinfoGetter) GetService(node string) (string, error) {
	ret := _mock.Called(node)

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(node)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(node)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(node)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockinfoGetter_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type MockinfoGetter_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
//   - node
func (_e *MockinfoGetter_Expecter) GetService(node interface{}) *MockinfoGetter_GetService_Call {
	return &MockinfoGetter_GetService_Call{Call: _e.mock.On("GetService", node)}
}

func (_c *MockinfoGetter_GetService_Call) Run(run func(node string)) *MockinfoGetter_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockinfoGetter_GetService_Call) Return(s string, err error) *MockinfoGetter_GetService_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockinfoGetter_GetService_Call) RunAndReturn(run func(node string) (string, error)) *MockinfoGetter_GetService_Call {
	_c.Call.Return(run)
	return _c
}
