// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aerospike/backup-go/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRestoreHandler creates a new instance of MockRestoreHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestoreHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestoreHandler {
	mock := &MockRestoreHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestoreHandler is an autogenerated mock type for the RestoreHandler type
type MockRestoreHandler struct {
	mock.Mock
}

type MockRestoreHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestoreHandler) EXPECT() *MockRestoreHandler_Expecter {
	return &MockRestoreHandler_Expecter{mock: &_m.Mock}
}

// GetMetrics provides a mock function for the type MockRestoreHandler
func (_mock *MockRestoreHandler) GetMetrics() *models.Metrics {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 *models.Metrics
	if returnFunc, ok := ret.Get(0).(func() *models.Metrics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Metrics)
		}
	}
	return r0
}

// MockRestoreHandler_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockRestoreHandler_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
func (_e *MockRestoreHandler_Expecter) GetMetrics() *MockRestoreHandler_GetMetrics_Call {
	return &MockRestoreHandler_GetMetrics_Call{Call: _e.mock.On("GetMetrics")}
}

func (_c *MockRestoreHandler_GetMetrics_Call) Run(run func()) *MockRestoreHandler_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRestoreHandler_GetMetrics_Call) Return(metrics *models.Metrics) *MockRestoreHandler_GetMetrics_Call {
	_c.Call.Return(metrics)
	return _c
}

func (_c *MockRestoreHandler_GetMetrics_Call) RunAndReturn(run func() *models.Metrics) *MockRestoreHandler_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockRestoreHandler
func (_mock *MockRestoreHandler) GetStats() *models.RestoreStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *models.RestoreStats
	if returnFunc, ok := ret.Get(0).(func() *models.RestoreStats); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RestoreStats)
		}
	}
	return r0
}

// MockRestoreHandler_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockRestoreHandler_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockRestoreHandler_Expecter) GetStats() *MockRestoreHandler_GetStats_Call {
	return &MockRestoreHandler_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockRestoreHandler_GetStats_Call) Run(run func()) *MockRestoreHandler_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRestoreHandler_GetStats_Call) Return(restoreStats *models.RestoreStats) *MockRestoreHandler_GetStats_Call {
	_c.Call.Return(restoreStats)
	return _c
}

func (_c *MockRestoreHandler_GetStats_Call) RunAndReturn(run func() *models.RestoreStats) *MockRestoreHandler_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockRestoreHandler
func (_mock *MockRestoreHandler) Wait(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRestoreHandler_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockRestoreHandler_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRestoreHandler_Expecter) Wait(ctx interface{}) *MockRestoreHandler_Wait_Call {
	return &MockRestoreHandler_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *MockRestoreHandler_Wait_Call) Run(run func(ctx context.Context)) *MockRestoreHandler_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRestoreHandler_Wait_Call) Return(err error) *MockRestoreHandler_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRestoreHandler_Wait_Call) RunAndReturn(run func(ctx context.Context) error) *MockRestoreHandler_Wait_Call {
	_c.Call.Return(run)
	return _c
}
