// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aerospike/backup-go/pkg/asinfo/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerBackupInfo creates a new instance of MockServerBackupInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerBackupInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerBackupInfo {
	mock := &MockServerBackupInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerBackupInfo is an autogenerated mock type for the ServerBackupInfo type
type MockServerBackupInfo struct {
	mock.Mock
}

type MockServerBackupInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerBackupInfo) EXPECT() *MockServerBackupInfo_Expecter {
	return &MockServerBackupInfo_Expecter{mock: &_m.Mock}
}

// AbortBackup provides a mock function for the type MockServerBackupInfo
func (_mock *MockServerBackupInfo) AbortBackup(ctx context.Context, backupID string) error {
	ret := _mock.Called(ctx, backupID)

	if len(ret) == 0 {
		panic("no return value specified for AbortBackup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, backupID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerBackupInfo_AbortBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortBackup'
type MockServerBackupInfo_AbortBackup_Call struct {
	*mock.Call
}

// AbortBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - backupID string
func (_e *MockServerBackupInfo_Expecter) AbortBackup(ctx any, backupID any) *MockServerBackupInfo_AbortBackup_Call {
	return &MockServerBackupInfo_AbortBackup_Call{Call: _e.mock.On("AbortBackup", ctx, backupID)}
}

func (_c *MockServerBackupInfo_AbortBackup_Call) Run(run func(ctx context.Context, backupID string)) *MockServerBackupInfo_AbortBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerBackupInfo_AbortBackup_Call) Return(err error) *MockServerBackupInfo_AbortBackup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerBackupInfo_AbortBackup_Call) RunAndReturn(run func(ctx context.Context, backupID string) error) *MockServerBackupInfo_AbortBackup_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackupStatus provides a mock function for the type MockServerBackupInfo
func (_mock *MockServerBackupInfo) GetBackupStatus(ctx context.Context, jobID string) (*models.ResponseBackupState, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupStatus")
	}

	var r0 *models.ResponseBackupState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.ResponseBackupState, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.ResponseBackupState); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResponseBackupState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerBackupInfo_GetBackupStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackupStatus'
type MockServerBackupInfo_GetBackupStatus_Call struct {
	*mock.Call
}

// GetBackupStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockServerBackupInfo_Expecter) GetBackupStatus(ctx any, jobID any) *MockServerBackupInfo_GetBackupStatus_Call {
	return &MockServerBackupInfo_GetBackupStatus_Call{Call: _e.mock.On("GetBackupStatus", ctx, jobID)}
}

func (_c *MockServerBackupInfo_GetBackupStatus_Call) Run(run func(ctx context.Context, jobID string)) *MockServerBackupInfo_GetBackupStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerBackupInfo_GetBackupStatus_Call) Return(responseBackupState *models.ResponseBackupState, err error) *MockServerBackupInfo_GetBackupStatus_Call {
	_c.Call.Return(responseBackupState, err)
	return _c
}

func (_c *MockServerBackupInfo_GetBackupStatus_Call) RunAndReturn(run func(ctx context.Context, jobID string) (*models.ResponseBackupState, error)) *MockServerBackupInfo_GetBackupStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetRestoreStatus provides a mock function for the type MockServerBackupInfo
func (_mock *MockServerBackupInfo) GetRestoreStatus(ctx context.Context, namespace string) (string, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetRestoreStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerBackupInfo_GetRestoreStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRestoreStatus'
type MockServerBackupInfo_GetRestoreStatus_Call struct {
	*mock.Call
}

// GetRestoreStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockServerBackupInfo_Expecter) GetRestoreStatus(ctx any, namespace any) *MockServerBackupInfo_GetRestoreStatus_Call {
	return &MockServerBackupInfo_GetRestoreStatus_Call{Call: _e.mock.On("GetRestoreStatus", ctx, namespace)}
}

func (_c *MockServerBackupInfo_GetRestoreStatus_Call) Run(run func(ctx context.Context, namespace string)) *MockServerBackupInfo_GetRestoreStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerBackupInfo_GetRestoreStatus_Call) Return(s string, err error) *MockServerBackupInfo_GetRestoreStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockServerBackupInfo_GetRestoreStatus_Call) RunAndReturn(run func(ctx context.Context, namespace string) (string, error)) *MockServerBackupInfo_GetRestoreStatus_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareRestore provides a mock function for the type MockServerBackupInfo
func (_mock *MockServerBackupInfo) PrepareRestore(ctx context.Context, jobID string, namespace string) error {
	ret := _mock.Called(ctx, jobID, namespace)

	if len(ret) == 0 {
		panic("no return value specified for PrepareRestore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, jobID, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerBackupInfo_PrepareRestore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareRestore'
type MockServerBackupInfo_PrepareRestore_Call struct {
	*mock.Call
}

// PrepareRestore is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
//   - namespace string
func (_e *MockServerBackupInfo_Expecter) PrepareRestore(ctx any, jobID any, namespace any) *MockServerBackupInfo_PrepareRestore_Call {
	return &MockServerBackupInfo_PrepareRestore_Call{Call: _e.mock.On("PrepareRestore", ctx, jobID, namespace)}
}

func (_c *MockServerBackupInfo_PrepareRestore_Call) Run(run func(ctx context.Context, jobID string, namespace string)) *MockServerBackupInfo_PrepareRestore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerBackupInfo_PrepareRestore_Call) Return(err error) *MockServerBackupInfo_PrepareRestore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerBackupInfo_PrepareRestore_Call) RunAndReturn(run func(ctx context.Context, jobID string, namespace string) error) *MockServerBackupInfo_PrepareRestore_Call {
	_c.Call.Return(run)
	return _c
}

// StartBackup provides a mock function for the type MockServerBackupInfo
func (_mock *MockServerBackupInfo) StartBackup(ctx context.Context, request *models.RequestBackup) (string, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for StartBackup")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RequestBackup) (string, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RequestBackup) string); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.RequestBackup) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerBackupInfo_StartBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartBackup'
type MockServerBackupInfo_StartBackup_Call struct {
	*mock.Call
}

// StartBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - request *models.RequestBackup
func (_e *MockServerBackupInfo_Expecter) StartBackup(ctx any, request any) *MockServerBackupInfo_StartBackup_Call {
	return &MockServerBackupInfo_StartBackup_Call{Call: _e.mock.On("StartBackup", ctx, request)}
}

func (_c *MockServerBackupInfo_StartBackup_Call) Run(run func(ctx context.Context, request *models.RequestBackup)) *MockServerBackupInfo_StartBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.RequestBackup
		if args[1] != nil {
			arg1 = args[1].(*models.RequestBackup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerBackupInfo_StartBackup_Call) Return(s string, err error) *MockServerBackupInfo_StartBackup_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockServerBackupInfo_StartBackup_Call) RunAndReturn(run func(ctx context.Context, request *models.RequestBackup) (string, error)) *MockServerBackupInfo_StartBackup_Call {
	_c.Call.Return(run)
	return _c
}

// StartRestore provides a mock function for the type MockServerBackupInfo
func (_mock *MockServerBackupInfo) StartRestore(ctx context.Context, request *models.RequestRestore) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for StartRestore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RequestRestore) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerBackupInfo_StartRestore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartRestore'
type MockServerBackupInfo_StartRestore_Call struct {
	*mock.Call
}

// StartRestore is a helper method to define mock.On call
//   - ctx context.Context
//   - request *models.RequestRestore
func (_e *MockServerBackupInfo_Expecter) StartRestore(ctx any, request any) *MockServerBackupInfo_StartRestore_Call {
	return &MockServerBackupInfo_StartRestore_Call{Call: _e.mock.On("StartRestore", ctx, request)}
}

func (_c *MockServerBackupInfo_StartRestore_Call) Run(run func(ctx context.Context, request *models.RequestRestore)) *MockServerBackupInfo_StartRestore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.RequestRestore
		if args[1] != nil {
			arg1 = args[1].(*models.RequestRestore)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerBackupInfo_StartRestore_Call) Return(err error) *MockServerBackupInfo_StartRestore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerBackupInfo_StartRestore_Call) RunAndReturn(run func(ctx context.Context, request *models.RequestRestore) error) *MockServerBackupInfo_StartRestore_Call {
	_c.Call.Return(run)
	return _c
}
