// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockdataReader creates a new instance of MockdataReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdataReader[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdataReader[T] {
	mock := &MockdataReader[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockdataReader is an autogenerated mock type for the dataReader type
type MockdataReader[T any] struct {
	mock.Mock
}

type MockdataReader_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockdataReader[T]) EXPECT() *MockdataReader_Expecter[T] {
	return &MockdataReader_Expecter[T]{mock: &_m.Mock}
}

// Close provides a mock function for the type MockdataReader
func (_mock *MockdataReader[T]) Close() {
	_mock.Called()
	return
}

// MockdataReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockdataReader_Close_Call[T any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockdataReader_Expecter[T]) Close() *MockdataReader_Close_Call[T] {
	return &MockdataReader_Close_Call[T]{Call: _e.mock.On("Close")}
}

func (_c *MockdataReader_Close_Call[T]) Run(run func()) *MockdataReader_Close_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockdataReader_Close_Call[T]) Return() *MockdataReader_Close_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockdataReader_Close_Call[T]) RunAndReturn(run func()) *MockdataReader_Close_Call[T] {
	_c.Run(run)
	return _c
}

// Read provides a mock function for the type MockdataReader
func (_mock *MockdataReader[T]) Read() (T, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (T, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockdataReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockdataReader_Read_Call[T any] struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockdataReader_Expecter[T]) Read() *MockdataReader_Read_Call[T] {
	return &MockdataReader_Read_Call[T]{Call: _e.mock.On("Read")}
}

func (_c *MockdataReader_Read_Call[T]) Run(run func()) *MockdataReader_Read_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockdataReader_Read_Call[T]) Return(v T, err error) *MockdataReader_Read_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockdataReader_Read_Call[T]) RunAndReturn(run func() (T, error)) *MockdataReader_Read_Call[T] {
	_c.Call.Return(run)
	return _c
}
