// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWorker creates a new instance of MockWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorker[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorker[T] {
	mock := &MockWorker[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorker is an autogenerated mock type for the Worker type
type MockWorker[T any] struct {
	mock.Mock
}

type MockWorker_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockWorker[T]) EXPECT() *MockWorker_Expecter[T] {
	return &MockWorker_Expecter[T]{mock: &_m.Mock}
}

// GetMetrics provides a mock function for the type MockWorker
func (_mock *MockWorker[T]) GetMetrics() (int, int) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 int
	var r1 int
	if returnFunc, ok := ret.Get(0).(func() (int, int)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() int); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(int)
	}
	return r0, r1
}

// MockWorker_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockWorker_GetMetrics_Call[T any] struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
func (_e *MockWorker_Expecter[T]) GetMetrics() *MockWorker_GetMetrics_Call[T] {
	return &MockWorker_GetMetrics_Call[T]{Call: _e.mock.On("GetMetrics")}
}

func (_c *MockWorker_GetMetrics_Call[T]) Run(run func()) *MockWorker_GetMetrics_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWorker_GetMetrics_Call[T]) Return(n int, n1 int) *MockWorker_GetMetrics_Call[T] {
	_c.Call.Return(n, n1)
	return _c
}

func (_c *MockWorker_GetMetrics_Call[T]) RunAndReturn(run func() (int, int)) *MockWorker_GetMetrics_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockWorker
func (_mock *MockWorker[T]) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorker_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockWorker_Run_Call[T any] struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1
func (_e *MockWorker_Expecter[T]) Run(context1 interface{}) *MockWorker_Run_Call[T] {
	return &MockWorker_Run_Call[T]{Call: _e.mock.On("Run", context1)}
}

func (_c *MockWorker_Run_Call[T]) Run(run func(context1 context.Context)) *MockWorker_Run_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWorker_Run_Call[T]) Return(err error) *MockWorker_Run_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorker_Run_Call[T]) RunAndReturn(run func(context1 context.Context) error) *MockWorker_Run_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SetReceiveChan provides a mock function for the type MockWorker
func (_mock *MockWorker[T]) SetReceiveChan(vCh <-chan T) {
	_mock.Called(vCh)
	return
}

// MockWorker_SetReceiveChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReceiveChan'
type MockWorker_SetReceiveChan_Call[T any] struct {
	*mock.Call
}

// SetReceiveChan is a helper method to define mock.On call
//   - vCh
func (_e *MockWorker_Expecter[T]) SetReceiveChan(vCh interface{}) *MockWorker_SetReceiveChan_Call[T] {
	return &MockWorker_SetReceiveChan_Call[T]{Call: _e.mock.On("SetReceiveChan", vCh)}
}

func (_c *MockWorker_SetReceiveChan_Call[T]) Run(run func(vCh <-chan T)) *MockWorker_SetReceiveChan_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(<-chan T))
	})
	return _c
}

func (_c *MockWorker_SetReceiveChan_Call[T]) Return() *MockWorker_SetReceiveChan_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockWorker_SetReceiveChan_Call[T]) RunAndReturn(run func(vCh <-chan T)) *MockWorker_SetReceiveChan_Call[T] {
	_c.Run(run)
	return _c
}

// SetSendChan provides a mock function for the type MockWorker
func (_mock *MockWorker[T]) SetSendChan(vCh chan<- T) {
	_mock.Called(vCh)
	return
}

// MockWorker_SetSendChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSendChan'
type MockWorker_SetSendChan_Call[T any] struct {
	*mock.Call
}

// SetSendChan is a helper method to define mock.On call
//   - vCh
func (_e *MockWorker_Expecter[T]) SetSendChan(vCh interface{}) *MockWorker_SetSendChan_Call[T] {
	return &MockWorker_SetSendChan_Call[T]{Call: _e.mock.On("SetSendChan", vCh)}
}

func (_c *MockWorker_SetSendChan_Call[T]) Run(run func(vCh chan<- T)) *MockWorker_SetSendChan_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan<- T))
	})
	return _c
}

func (_c *MockWorker_SetSendChan_Call[T]) Return() *MockWorker_SetSendChan_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockWorker_SetSendChan_Call[T]) RunAndReturn(run func(vCh chan<- T)) *MockWorker_SetSendChan_Call[T] {
	_c.Run(run)
	return _c
}
