// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cloud.google.com/go/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Bucket provides a mock function for the type MockClient
func (_mock *MockClient) Bucket(name string) *storage.BucketHandle {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Bucket")
	}

	var r0 *storage.BucketHandle
	if returnFunc, ok := ret.Get(0).(func(string) *storage.BucketHandle); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.BucketHandle)
		}
	}
	return r0
}

// MockClient_Bucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bucket'
type MockClient_Bucket_Call struct {
	*mock.Call
}

// Bucket is a helper method to define mock.On call
//   - name string
func (_e *MockClient_Expecter) Bucket(name interface{}) *MockClient_Bucket_Call {
	return &MockClient_Bucket_Call{Call: _e.mock.On("Bucket", name)}
}

func (_c *MockClient_Bucket_Call) Run(run func(name string)) *MockClient_Bucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Bucket_Call) Return(bucketHandle *storage.BucketHandle) *MockClient_Bucket_Call {
	_c.Call.Return(bucketHandle)
	return _c
}

func (_c *MockClient_Bucket_Call) RunAndReturn(run func(name string) *storage.BucketHandle) *MockClient_Bucket_Call {
	_c.Call.Return(run)
	return _c
}
