// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "github.com/aerospike/backup-go/models"
	mock "github.com/stretchr/testify/mock"
)

// MocksindexGetter is an autogenerated mock type for the sindexGetter type
type MocksindexGetter struct {
	mock.Mock
}

type MocksindexGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MocksindexGetter) EXPECT() *MocksindexGetter_Expecter {
	return &MocksindexGetter_Expecter{mock: &_m.Mock}
}

// GetSIndexes provides a mock function with given fields: namespace
func (_m *MocksindexGetter) GetSIndexes(namespace string) ([]*models.SIndex, error) {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetSIndexes")
	}

	var r0 []*models.SIndex
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.SIndex, error)); ok {
		return rf(namespace)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.SIndex); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SIndex)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MocksindexGetter_GetSIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSIndexes'
type MocksindexGetter_GetSIndexes_Call struct {
	*mock.Call
}

// GetSIndexes is a helper method to define mock.On call
//   - namespace string
func (_e *MocksindexGetter_Expecter) GetSIndexes(namespace interface{}) *MocksindexGetter_GetSIndexes_Call {
	return &MocksindexGetter_GetSIndexes_Call{Call: _e.mock.On("GetSIndexes", namespace)}
}

func (_c *MocksindexGetter_GetSIndexes_Call) Run(run func(namespace string)) *MocksindexGetter_GetSIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MocksindexGetter_GetSIndexes_Call) Return(_a0 []*models.SIndex, _a1 error) *MocksindexGetter_GetSIndexes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MocksindexGetter_GetSIndexes_Call) RunAndReturn(run func(string) ([]*models.SIndex, error)) *MocksindexGetter_GetSIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocksindexGetter creates a new instance of MocksindexGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksindexGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocksindexGetter {
	mock := &MocksindexGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
