// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aerospike/backup-go/models"
	mock "github.com/stretchr/testify/mock"
)

// MockudfGetter is an autogenerated mock type for the udfGetter type
type MockudfGetter struct {
	mock.Mock
}

type MockudfGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockudfGetter) EXPECT() *MockudfGetter_Expecter {
	return &MockudfGetter_Expecter{mock: &_m.Mock}
}

// GetUDFs provides a mock function with given fields:
func (_m *MockudfGetter) GetUDFs() ([]*models.UDF, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUDFs")
	}

	var r0 []*models.UDF
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.UDF, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.UDF); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UDF)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockudfGetter_GetUDFs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUDFs'
type MockudfGetter_GetUDFs_Call struct {
	*mock.Call
}

// GetUDFs is a helper method to define mock.On call
func (_e *MockudfGetter_Expecter) GetUDFs() *MockudfGetter_GetUDFs_Call {
	return &MockudfGetter_GetUDFs_Call{Call: _e.mock.On("GetUDFs")}
}

func (_c *MockudfGetter_GetUDFs_Call) Run(run func()) *MockudfGetter_GetUDFs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockudfGetter_GetUDFs_Call) Return(_a0 []*models.UDF, _a1 error) *MockudfGetter_GetUDFs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockudfGetter_GetUDFs_Call) RunAndReturn(run func() ([]*models.UDF, error)) *MockudfGetter_GetUDFs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockudfGetter creates a new instance of MockudfGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockudfGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockudfGetter {
	mock := &MockudfGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
