name: Promote Image

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  promote-to-jfrog-prod-env:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Get Metadata
        run: |
          git fetch --tags --depth=1
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "BUNDLE_VERSION=$LATEST_TAG" >> $GITHUB_ENV
          echo "BUNDLE_NAME=aerospike-backup-tools" >> $GITHUB_ENV

      - name: Login to JFrog
        uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 # v4.5.11
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          JF_PROJECT: ${{ vars.JFROG_CLI_BUILD_PROJECT }}

      - name: Promote to JFrog PROD Environment
        run: |
          jfrog release-bundle-promote "$BUNDLE_NAME" "$BUNDLE_VERSION" \
          --signing-key="aerospike" --project="ecosystem" PROD

  promote-to-dockerhub:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - name: Get Metadata
        run: |
          git fetch --tags --depth=1
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "TAG=${LATEST_TAG#v}" >> $GITHUB_ENV
          echo "REPO_NAME=aerospike-backup-tools" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3.11.0
      - name: Login to JFrog Artifactory
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: aerospike.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Pull Images from JFrog
        env:
          TAG: ${{env.TAG}}
          REPO_NAME: ${{env.REPO_NAME}}
          ARTIFACTORY_CONTAINER_DEV: ${{ vars.ARTIFACTORY_CONTAINER_DEV }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          JF_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
        run: |
          set -euo pipefail
          
          url="https://aerospike.jfrog.io/artifactory/$ARTIFACTORY_CONTAINER_DEV/$REPO_NAME/$TAG/list.manifest.json"
          amd64_digest="$(curl -sSL -u$JF_USERNAME:$JF_ACCESS_TOKEN "$url" | jq -r '.manifests[] | select(.platform.architecture == "amd64") | .digest')"
          arm64_digest="$(curl -sSL -u$JF_USERNAME:$JF_ACCESS_TOKEN "$url" | jq -r '.manifests[] | select(.platform.architecture == "arm64") | .digest')"
          
          if [[ -z "$amd64_digest" || -z "$arm64_digest" ]]; then
          echo "Error: Could not resolve image digests."
          exit 1
          fi
          
          docker pull "aerospike.jfrog.io/$ARTIFACTORY_CONTAINER_DEV/$REPO_NAME@$amd64_digest"
          docker pull "aerospike.jfrog.io/$ARTIFACTORY_CONTAINER_DEV/$REPO_NAME@$arm64_digest"
          
          echo "AMD64_DIGEST=$amd64_digest" >> $GITHUB_ENV
          echo "ARM64_DIGEST=$arm64_digest" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Promote to DockerHub
        env:
          TAG: ${{env.TAG}}
          REPO_NAME: ${{env.REPO_NAME}}
          ARTIFACTORY_CONTAINER_DEV: ${{ vars.ARTIFACTORY_CONTAINER_DEV }}

        run: |
          set -euo pipefail
          
          amd64_tag="aerospike/$REPO_NAME:$TAG-amd64"
          arm64_tag="aerospike/$REPO_NAME:$TAG-arm64"
          multiarch_tag="aerospike/$REPO_NAME:$TAG"
          
          docker tag "aerospike.jfrog.io/$ARTIFACTORY_CONTAINER_DEV/$REPO_NAME@$AMD64_DIGEST" "$amd64_tag"
          docker tag "aerospike.jfrog.io/$ARTIFACTORY_CONTAINER_DEV/$REPO_NAME@$ARM64_DIGEST" "$arm64_tag"
          
          docker push "$amd64_tag"
          docker push "$arm64_tag"
          
          docker manifest create "$multiarch_tag"  "$amd64_tag" "$arm64_tag"
          
          docker manifest annotate "$multiarch_tag" "$amd64_tag" --arch amd64
          docker manifest annotate "$multiarch_tag" "$arm64_tag" --arch arm64
          
          docker manifest push "$multiarch_tag"
