name: Snyk scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@9adf32b1121593767fc3c057af55b55db032dc04
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          snyk-version: v1.1297.3
          args: --all-projects --sarif-file-output=snyk.sarif

      - name: Handle undefined security-severity
        run: |
          if [ -f snyk.sarif ]; then sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk.sarif; fi

      - name: Check output file
        id: out-file
        run: |
          if test -f "snyk.sarif"; then
            echo "::set-output name=exists::true"; else
            echo "::set-output name=exists::false"
          fi

      - name: Upload result to GitHub Code Scanning
        if: steps.out-file.outputs.exists == 'true'
        uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
        with:
          sarif_file: snyk.sarif
