name: Snyk scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@9adf32b1121593767fc3c057af55b55db032dc04
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          snyk-version: v1.1297.3
          args: --all-projects --sarif-file-output=snyk.sarif

      - name: Handle undefined security-severity
        run: |
          if [ -f snyk.sarif ]; then sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk.sarif; fi

      - name: Check output file
        id: out-file
        run: |
          if test -f "snyk.sarif"; then
            echo "::set-output name=exists::true"; else
            echo "::set-output name=exists::false"
          fi

      - name: Upload result to GitHub Code Scanning
        if: steps.out-file.outputs.exists == 'true'
        uses: github/codeql-action/upload-sarif@87557b9c84dde89fdd9b10e88954ac2f4248e463 # v4.36.1
        with:
          sarif_file: snyk.sarif
